//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.36213
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace GMM_FIELD {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DataSet1")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSet1 : global::System.Data.DataSet {
        
        private GMMDataTable tableGMM;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DataSet1() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DataSet1(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["GMM"] != null)) {
                    base.Tables.Add(new GMMDataTable(ds.Tables["GMM"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GMMDataTable GMM {
            get {
                return this.tableGMM;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["GMM"] != null)) {
                    base.Tables.Add(new GMMDataTable(ds.Tables["GMM"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableGMM = ((GMMDataTable)(base.Tables["GMM"]));
            if ((initTable == true)) {
                if ((this.tableGMM != null)) {
                    this.tableGMM.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSet1.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableGMM = new GMMDataTable();
            base.Tables.Add(this.tableGMM);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeGMM() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DataSet1 ds = new DataSet1();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void GMMRowChangeEventHandler(object sender, GMMRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class GMMDataTable : global::System.Data.TypedTableBase<GMMRow> {
            
            private global::System.Data.DataColumn columnКод_сферы;
            
            private global::System.Data.DataColumn columnКоличество_сфер;
            
            private global::System.Data.DataColumn columnОписание_рассчета;
            
            private global::System.Data.DataColumn _columnКоличество_ориентаций_nbeta_;
            
            private global::System.Data.DataColumn _columnКоличество_ориентаций_nthet_;
            
            private global::System.Data.DataColumn _columnКоличество_ориентаций_nphai_;
            
            private global::System.Data.DataColumn _columnОриентация_betami_;
            
            private global::System.Data.DataColumn _columnОриентация_betamx_;
            
            private global::System.Data.DataColumn _columnОриентация_thetmi_;
            
            private global::System.Data.DataColumn _columnОриентация_thetmx_;
            
            private global::System.Data.DataColumn _columnОриентация_phaimi_;
            
            private global::System.Data.DataColumn _columnОриентация_phaimx_;
            
            private global::System.Data.DataColumn columnИтерация_по_схеме_X;
            
            private global::System.Data.DataColumn columnИтерация_по_схеме_Y;
            
            private global::System.Data.DataColumn columnМаксимальное_количество_итераций;
            
            private global::System.Data.DataColumn columnПорядок_управления_рассеиванием;
            
            private global::System.Data.DataColumn columnПогрешность_ошибки;
            
            private global::System.Data.DataColumn columnКритерий_сходимости;
            
            private global::System.Data.DataColumn columnИндекс_взаимодействия;
            
            private global::System.Data.DataColumn columnДлина_волны;
            
            private global::System.Data.DataColumn columnДата_расчета;
            
            private global::System.Data.DataColumn columnВремя_расчета;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GMMDataTable() {
                this.TableName = "GMM";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal GMMDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected GMMDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Код_сферыColumn {
                get {
                    return this.columnКод_сферы;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Количество_сферColumn {
                get {
                    return this.columnКоличество_сфер;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Описание_рассчетаColumn {
                get {
                    return this.columnОписание_рассчета;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Количество_ориентаций_nbeta_Column {
                get {
                    return this._columnКоличество_ориентаций_nbeta_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Количество_ориентаций_nthet_Column {
                get {
                    return this._columnКоличество_ориентаций_nthet_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Количество_ориентаций_nphai_Column {
                get {
                    return this._columnКоличество_ориентаций_nphai_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Ориентация_betami_Column {
                get {
                    return this._columnОриентация_betami_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Ориентация_betamx_Column {
                get {
                    return this._columnОриентация_betamx_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Ориентация_thetmi_Column {
                get {
                    return this._columnОриентация_thetmi_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Ориентация_thetmx_Column {
                get {
                    return this._columnОриентация_thetmx_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Ориентация_phaimi_Column {
                get {
                    return this._columnОриентация_phaimi_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _Ориентация_phaimx_Column {
                get {
                    return this._columnОриентация_phaimx_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Итерация_по_схеме_XColumn {
                get {
                    return this.columnИтерация_по_схеме_X;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Итерация_по_схеме_YColumn {
                get {
                    return this.columnИтерация_по_схеме_Y;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Максимальное_количество_итерацийColumn {
                get {
                    return this.columnМаксимальное_количество_итераций;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Порядок_управления_рассеиваниемColumn {
                get {
                    return this.columnПорядок_управления_рассеиванием;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Погрешность_ошибкиColumn {
                get {
                    return this.columnПогрешность_ошибки;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Критерий_сходимостиColumn {
                get {
                    return this.columnКритерий_сходимости;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Индекс_взаимодействияColumn {
                get {
                    return this.columnИндекс_взаимодействия;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Длина_волныColumn {
                get {
                    return this.columnДлина_волны;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Дата_расчетаColumn {
                get {
                    return this.columnДата_расчета;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn Время_расчетаColumn {
                get {
                    return this.columnВремя_расчета;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GMMRow this[int index] {
                get {
                    return ((GMMRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GMMRowChangeEventHandler GMMRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GMMRowChangeEventHandler GMMRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GMMRowChangeEventHandler GMMRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event GMMRowChangeEventHandler GMMRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddGMMRow(GMMRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GMMRow AddGMMRow(
                        int Количество_сфер, 
                        string Описание_рассчета, 
                        int _Количество_ориентаций_nbeta_, 
                        int _Количество_ориентаций_nthet_, 
                        int _Количество_ориентаций_nphai_, 
                        int _Ориентация_betami_, 
                        int _Ориентация_betamx_, 
                        int _Ориентация_thetmi_, 
                        int _Ориентация_thetmx_, 
                        int _Ориентация_phaimi_, 
                        int _Ориентация_phaimx_, 
                        double Итерация_по_схеме_X, 
                        double Итерация_по_схеме_Y, 
                        int Максимальное_количество_итераций, 
                        int Порядок_управления_рассеиванием, 
                        double Погрешность_ошибки, 
                        double Критерий_сходимости, 
                        int Индекс_взаимодействия, 
                        double Длина_волны, 
                        string Дата_расчета, 
                        string Время_расчета) {
                GMMRow rowGMMRow = ((GMMRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        Количество_сфер,
                        Описание_рассчета,
                        _Количество_ориентаций_nbeta_,
                        _Количество_ориентаций_nthet_,
                        _Количество_ориентаций_nphai_,
                        _Ориентация_betami_,
                        _Ориентация_betamx_,
                        _Ориентация_thetmi_,
                        _Ориентация_thetmx_,
                        _Ориентация_phaimi_,
                        _Ориентация_phaimx_,
                        Итерация_по_схеме_X,
                        Итерация_по_схеме_Y,
                        Максимальное_количество_итераций,
                        Порядок_управления_рассеиванием,
                        Погрешность_ошибки,
                        Критерий_сходимости,
                        Индекс_взаимодействия,
                        Длина_волны,
                        Дата_расчета,
                        Время_расчета};
                rowGMMRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowGMMRow);
                return rowGMMRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GMMRow FindByКод_сферы(int Код_сферы) {
                return ((GMMRow)(this.Rows.Find(new object[] {
                            Код_сферы})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                GMMDataTable cln = ((GMMDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new GMMDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnКод_сферы = base.Columns["Код_сферы"];
                this.columnКоличество_сфер = base.Columns["Количество_сфер"];
                this.columnОписание_рассчета = base.Columns["Описание_рассчета"];
                this._columnКоличество_ориентаций_nbeta_ = base.Columns["Количество_ориентаций(nbeta)"];
                this._columnКоличество_ориентаций_nthet_ = base.Columns["Количество_ориентаций(nthet)"];
                this._columnКоличество_ориентаций_nphai_ = base.Columns["Количество_ориентаций(nphai)"];
                this._columnОриентация_betami_ = base.Columns["Ориентация(betami)"];
                this._columnОриентация_betamx_ = base.Columns["Ориентация(betamx)"];
                this._columnОриентация_thetmi_ = base.Columns["Ориентация(thetmi)"];
                this._columnОриентация_thetmx_ = base.Columns["Ориентация(thetmx)"];
                this._columnОриентация_phaimi_ = base.Columns["Ориентация(phaimi)"];
                this._columnОриентация_phaimx_ = base.Columns["Ориентация(phaimx)"];
                this.columnИтерация_по_схеме_X = base.Columns["Итерация_по_схеме_X"];
                this.columnИтерация_по_схеме_Y = base.Columns["Итерация_по_схеме_Y"];
                this.columnМаксимальное_количество_итераций = base.Columns["Максимальное_количество_итераций"];
                this.columnПорядок_управления_рассеиванием = base.Columns["Порядок_управления_рассеиванием"];
                this.columnПогрешность_ошибки = base.Columns["Погрешность_ошибки"];
                this.columnКритерий_сходимости = base.Columns["Критерий_сходимости"];
                this.columnИндекс_взаимодействия = base.Columns["Индекс_взаимодействия"];
                this.columnДлина_волны = base.Columns["Длина_волны"];
                this.columnДата_расчета = base.Columns["Дата_расчета"];
                this.columnВремя_расчета = base.Columns["Время расчета"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnКод_сферы = new global::System.Data.DataColumn("Код_сферы", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnКод_сферы);
                this.columnКоличество_сфер = new global::System.Data.DataColumn("Количество_сфер", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnКоличество_сфер);
                this.columnОписание_рассчета = new global::System.Data.DataColumn("Описание_рассчета", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnОписание_рассчета);
                this._columnКоличество_ориентаций_nbeta_ = new global::System.Data.DataColumn("Количество_ориентаций(nbeta)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnКоличество_ориентаций_nbeta_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnКоличество_ориентаций_nbeta_");
                this._columnКоличество_ориентаций_nbeta_.ExtendedProperties.Add("Generator_UserColumnName", "Количество_ориентаций(nbeta)");
                base.Columns.Add(this._columnКоличество_ориентаций_nbeta_);
                this._columnКоличество_ориентаций_nthet_ = new global::System.Data.DataColumn("Количество_ориентаций(nthet)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnКоличество_ориентаций_nthet_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnКоличество_ориентаций_nthet_");
                this._columnКоличество_ориентаций_nthet_.ExtendedProperties.Add("Generator_UserColumnName", "Количество_ориентаций(nthet)");
                base.Columns.Add(this._columnКоличество_ориентаций_nthet_);
                this._columnКоличество_ориентаций_nphai_ = new global::System.Data.DataColumn("Количество_ориентаций(nphai)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnКоличество_ориентаций_nphai_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnКоличество_ориентаций_nphai_");
                this._columnКоличество_ориентаций_nphai_.ExtendedProperties.Add("Generator_UserColumnName", "Количество_ориентаций(nphai)");
                base.Columns.Add(this._columnКоличество_ориентаций_nphai_);
                this._columnОриентация_betami_ = new global::System.Data.DataColumn("Ориентация(betami)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnОриентация_betami_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnОриентация_betami_");
                this._columnОриентация_betami_.ExtendedProperties.Add("Generator_UserColumnName", "Ориентация(betami)");
                base.Columns.Add(this._columnОриентация_betami_);
                this._columnОриентация_betamx_ = new global::System.Data.DataColumn("Ориентация(betamx)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnОриентация_betamx_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnОриентация_betamx_");
                this._columnОриентация_betamx_.ExtendedProperties.Add("Generator_UserColumnName", "Ориентация(betamx)");
                base.Columns.Add(this._columnОриентация_betamx_);
                this._columnОриентация_thetmi_ = new global::System.Data.DataColumn("Ориентация(thetmi)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnОриентация_thetmi_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnОриентация_thetmi_");
                this._columnОриентация_thetmi_.ExtendedProperties.Add("Generator_UserColumnName", "Ориентация(thetmi)");
                base.Columns.Add(this._columnОриентация_thetmi_);
                this._columnОриентация_thetmx_ = new global::System.Data.DataColumn("Ориентация(thetmx)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnОриентация_thetmx_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnОриентация_thetmx_");
                this._columnОриентация_thetmx_.ExtendedProperties.Add("Generator_UserColumnName", "Ориентация(thetmx)");
                base.Columns.Add(this._columnОриентация_thetmx_);
                this._columnОриентация_phaimi_ = new global::System.Data.DataColumn("Ориентация(phaimi)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnОриентация_phaimi_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnОриентация_phaimi_");
                this._columnОриентация_phaimi_.ExtendedProperties.Add("Generator_UserColumnName", "Ориентация(phaimi)");
                base.Columns.Add(this._columnОриентация_phaimi_);
                this._columnОриентация_phaimx_ = new global::System.Data.DataColumn("Ориентация(phaimx)", typeof(int), null, global::System.Data.MappingType.Element);
                this._columnОриентация_phaimx_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnОриентация_phaimx_");
                this._columnОриентация_phaimx_.ExtendedProperties.Add("Generator_UserColumnName", "Ориентация(phaimx)");
                base.Columns.Add(this._columnОриентация_phaimx_);
                this.columnИтерация_по_схеме_X = new global::System.Data.DataColumn("Итерация_по_схеме_X", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnИтерация_по_схеме_X);
                this.columnИтерация_по_схеме_Y = new global::System.Data.DataColumn("Итерация_по_схеме_Y", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnИтерация_по_схеме_Y);
                this.columnМаксимальное_количество_итераций = new global::System.Data.DataColumn("Максимальное_количество_итераций", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnМаксимальное_количество_итераций);
                this.columnПорядок_управления_рассеиванием = new global::System.Data.DataColumn("Порядок_управления_рассеиванием", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnПорядок_управления_рассеиванием);
                this.columnПогрешность_ошибки = new global::System.Data.DataColumn("Погрешность_ошибки", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnПогрешность_ошибки);
                this.columnКритерий_сходимости = new global::System.Data.DataColumn("Критерий_сходимости", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnКритерий_сходимости);
                this.columnИндекс_взаимодействия = new global::System.Data.DataColumn("Индекс_взаимодействия", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnИндекс_взаимодействия);
                this.columnДлина_волны = new global::System.Data.DataColumn("Длина_волны", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnДлина_волны);
                this.columnДата_расчета = new global::System.Data.DataColumn("Дата_расчета", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnДата_расчета);
                this.columnВремя_расчета = new global::System.Data.DataColumn("Время расчета", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnВремя_расчета);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnКод_сферы}, true));
                this.columnКод_сферы.AutoIncrement = true;
                this.columnКод_сферы.AllowDBNull = false;
                this.columnКод_сферы.Unique = true;
                this.columnОписание_рассчета.MaxLength = 255;
                this.columnДата_расчета.MaxLength = 255;
                this.columnВремя_расчета.MaxLength = 255;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GMMRow NewGMMRow() {
                return ((GMMRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new GMMRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(GMMRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GMMRowChanged != null)) {
                    this.GMMRowChanged(this, new GMMRowChangeEvent(((GMMRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GMMRowChanging != null)) {
                    this.GMMRowChanging(this, new GMMRowChangeEvent(((GMMRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GMMRowDeleted != null)) {
                    this.GMMRowDeleted(this, new GMMRowChangeEvent(((GMMRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GMMRowDeleting != null)) {
                    this.GMMRowDeleting(this, new GMMRowChangeEvent(((GMMRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveGMMRow(GMMRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSet1 ds = new DataSet1();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "GMMDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class GMMRow : global::System.Data.DataRow {
            
            private GMMDataTable tableGMM;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal GMMRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableGMM = ((GMMDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Код_сферы {
                get {
                    return ((int)(this[this.tableGMM.Код_сферыColumn]));
                }
                set {
                    this[this.tableGMM.Код_сферыColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Количество_сфер {
                get {
                    try {
                        return ((int)(this[this.tableGMM.Количество_сферColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Количество_сфер\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Количество_сферColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Описание_рассчета {
                get {
                    try {
                        return ((string)(this[this.tableGMM.Описание_рассчетаColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Описание_рассчета\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Описание_рассчетаColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Количество_ориентаций_nbeta_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Количество_ориентаций_nbeta_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Количество_ориентаций(nbeta)\' в таблице \'GMM\' равно DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableGMM._Количество_ориентаций_nbeta_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Количество_ориентаций_nthet_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Количество_ориентаций_nthet_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Количество_ориентаций(nthet)\' в таблице \'GMM\' равно DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableGMM._Количество_ориентаций_nthet_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Количество_ориентаций_nphai_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Количество_ориентаций_nphai_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Количество_ориентаций(nphai)\' в таблице \'GMM\' равно DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableGMM._Количество_ориентаций_nphai_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Ориентация_betami_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Ориентация_betami_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Ориентация(betami)\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM._Ориентация_betami_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Ориентация_betamx_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Ориентация_betamx_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Ориентация(betamx)\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM._Ориентация_betamx_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Ориентация_thetmi_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Ориентация_thetmi_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Ориентация(thetmi)\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM._Ориентация_thetmi_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Ориентация_thetmx_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Ориентация_thetmx_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Ориентация(thetmx)\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM._Ориентация_thetmx_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Ориентация_phaimi_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Ориентация_phaimi_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Ориентация(phaimi)\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM._Ориентация_phaimi_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int _Ориентация_phaimx_ {
                get {
                    try {
                        return ((int)(this[this.tableGMM._Ориентация_phaimx_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Ориентация(phaimx)\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM._Ориентация_phaimx_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double Итерация_по_схеме_X {
                get {
                    try {
                        return ((double)(this[this.tableGMM.Итерация_по_схеме_XColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Итерация_по_схеме_X\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Итерация_по_схеме_XColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double Итерация_по_схеме_Y {
                get {
                    try {
                        return ((double)(this[this.tableGMM.Итерация_по_схеме_YColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Итерация_по_схеме_Y\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Итерация_по_схеме_YColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Максимальное_количество_итераций {
                get {
                    try {
                        return ((int)(this[this.tableGMM.Максимальное_количество_итерацийColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Максимальное_количество_итераций\' в таблице \'GMM\' равно DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Максимальное_количество_итерацийColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Порядок_управления_рассеиванием {
                get {
                    try {
                        return ((int)(this[this.tableGMM.Порядок_управления_рассеиваниемColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Порядок_управления_рассеиванием\' в таблице \'GMM\' равно DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableGMM.Порядок_управления_рассеиваниемColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double Погрешность_ошибки {
                get {
                    try {
                        return ((double)(this[this.tableGMM.Погрешность_ошибкиColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Погрешность_ошибки\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Погрешность_ошибкиColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double Критерий_сходимости {
                get {
                    try {
                        return ((double)(this[this.tableGMM.Критерий_сходимостиColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Критерий_сходимости\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Критерий_сходимостиColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Индекс_взаимодействия {
                get {
                    try {
                        return ((int)(this[this.tableGMM.Индекс_взаимодействияColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Индекс_взаимодействия\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Индекс_взаимодействияColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double Длина_волны {
                get {
                    try {
                        return ((double)(this[this.tableGMM.Длина_волныColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Длина_волны\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Длина_волныColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Дата_расчета {
                get {
                    try {
                        return ((string)(this[this.tableGMM.Дата_расчетаColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Дата_расчета\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Дата_расчетаColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string Время_расчета {
                get {
                    try {
                        return ((string)(this[this.tableGMM.Время_расчетаColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("Значение для столбца \'Время расчета\' в таблице \'GMM\' равно DBNull.", e);
                    }
                }
                set {
                    this[this.tableGMM.Время_расчетаColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsКоличество_сферNull() {
                return this.IsNull(this.tableGMM.Количество_сферColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetКоличество_сферNull() {
                this[this.tableGMM.Количество_сферColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsОписание_рассчетаNull() {
                return this.IsNull(this.tableGMM.Описание_рассчетаColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetОписание_рассчетаNull() {
                this[this.tableGMM.Описание_рассчетаColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Количество_ориентаций_nbeta_Null() {
                return this.IsNull(this.tableGMM._Количество_ориентаций_nbeta_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Количество_ориентаций_nbeta_Null() {
                this[this.tableGMM._Количество_ориентаций_nbeta_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Количество_ориентаций_nthet_Null() {
                return this.IsNull(this.tableGMM._Количество_ориентаций_nthet_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Количество_ориентаций_nthet_Null() {
                this[this.tableGMM._Количество_ориентаций_nthet_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Количество_ориентаций_nphai_Null() {
                return this.IsNull(this.tableGMM._Количество_ориентаций_nphai_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Количество_ориентаций_nphai_Null() {
                this[this.tableGMM._Количество_ориентаций_nphai_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Ориентация_betami_Null() {
                return this.IsNull(this.tableGMM._Ориентация_betami_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Ориентация_betami_Null() {
                this[this.tableGMM._Ориентация_betami_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Ориентация_betamx_Null() {
                return this.IsNull(this.tableGMM._Ориентация_betamx_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Ориентация_betamx_Null() {
                this[this.tableGMM._Ориентация_betamx_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Ориентация_thetmi_Null() {
                return this.IsNull(this.tableGMM._Ориентация_thetmi_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Ориентация_thetmi_Null() {
                this[this.tableGMM._Ориентация_thetmi_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Ориентация_thetmx_Null() {
                return this.IsNull(this.tableGMM._Ориентация_thetmx_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Ориентация_thetmx_Null() {
                this[this.tableGMM._Ориентация_thetmx_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Ориентация_phaimi_Null() {
                return this.IsNull(this.tableGMM._Ориентация_phaimi_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Ориентация_phaimi_Null() {
                this[this.tableGMM._Ориентация_phaimi_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_Ориентация_phaimx_Null() {
                return this.IsNull(this.tableGMM._Ориентация_phaimx_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_Ориентация_phaimx_Null() {
                this[this.tableGMM._Ориентация_phaimx_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsИтерация_по_схеме_XNull() {
                return this.IsNull(this.tableGMM.Итерация_по_схеме_XColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetИтерация_по_схеме_XNull() {
                this[this.tableGMM.Итерация_по_схеме_XColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsИтерация_по_схеме_YNull() {
                return this.IsNull(this.tableGMM.Итерация_по_схеме_YColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetИтерация_по_схеме_YNull() {
                this[this.tableGMM.Итерация_по_схеме_YColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsМаксимальное_количество_итерацийNull() {
                return this.IsNull(this.tableGMM.Максимальное_количество_итерацийColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetМаксимальное_количество_итерацийNull() {
                this[this.tableGMM.Максимальное_количество_итерацийColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsПорядок_управления_рассеиваниемNull() {
                return this.IsNull(this.tableGMM.Порядок_управления_рассеиваниемColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetПорядок_управления_рассеиваниемNull() {
                this[this.tableGMM.Порядок_управления_рассеиваниемColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsПогрешность_ошибкиNull() {
                return this.IsNull(this.tableGMM.Погрешность_ошибкиColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetПогрешность_ошибкиNull() {
                this[this.tableGMM.Погрешность_ошибкиColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsКритерий_сходимостиNull() {
                return this.IsNull(this.tableGMM.Критерий_сходимостиColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetКритерий_сходимостиNull() {
                this[this.tableGMM.Критерий_сходимостиColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsИндекс_взаимодействияNull() {
                return this.IsNull(this.tableGMM.Индекс_взаимодействияColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetИндекс_взаимодействияNull() {
                this[this.tableGMM.Индекс_взаимодействияColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsДлина_волныNull() {
                return this.IsNull(this.tableGMM.Длина_волныColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetДлина_волныNull() {
                this[this.tableGMM.Длина_волныColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsДата_расчетаNull() {
                return this.IsNull(this.tableGMM.Дата_расчетаColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetДата_расчетаNull() {
                this[this.tableGMM.Дата_расчетаColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsВремя_расчетаNull() {
                return this.IsNull(this.tableGMM.Время_расчетаColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetВремя_расчетаNull() {
                this[this.tableGMM.Время_расчетаColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class GMMRowChangeEvent : global::System.EventArgs {
            
            private GMMRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GMMRowChangeEvent(GMMRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public GMMRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591